SELECT C.HACKER_ID, H.NAME, COUNT(C.HACKER_ID) AS FIN
FROM HACKERS H
INNER JOIN CHALLENGES C ON (C.HACKER_ID = H.HACKER_ID)
GROUP BY C.HACKER_ID, H.NAME
HAVING 
    FIN = 
    (SELECT MAX(AUX.COUNTER)
    FROM(SELECT COUNT(HACKER_ID) AS COUNTER
        FROM CHALLENGES
        GROUP BY HACKER_ID
        ORDER BY HACKER_ID)AS AUX)
    OR FIN IN 
    (SELECT AUXT.COUNTER
    FROM(SELECT COUNT(*) AS COUNTER
        FROM CHALLENGES
        GROUP BY HACKER_ID) AS AUXT
    GROUP BY AUXT.COUNTER
    HAVING COUNT(AUXT.COUNTER) = 1)
ORDER BY FIN DESC, C.HACKER_ID;