SELECT 
FUNC1.X,
FUNC1.Y 
FROM FUNCTIONS FUNC1
INNER JOIN FUNCTIONS FUNC2 ON (FUNC1.X = FUNC2.Y 
                               AND FUNC1.Y = FUNC2.X)
GROUP BY FUNC1.X, FUNC1.Y
HAVING COUNT(FUNC1.X)>1 OR FUNC1.X<FUNC1.Y
ORDER BY FUNC1.X;
