SELECT 
CONCAT(NAME,'(',LEFT(OCCUPATION,1),')') AS COMP
FROM OCCUPATIONS
ORDER BY COMP ASC;

SELECT
CONCAT("There are a total of ",COUNT(OCCUPATION)," ",LOWER(OCCUPATION),"s.") AS NC 
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY NC ASC;