SELECT
H.HACKER_ID,
H.NAME
FROM HACKERS H, DIFFICULTY D, CHALLENGES C, SUBMISSIONS S
WHERE S.HACKER_ID = H.HACKER_ID
    AND S.CHALLENGE_ID = C.CHALLENGE_ID
    AND S.SCORE = D.SCORE
    AND C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(S.HACKER_ID) > 1
ORDER BY COUNT(S.HACKER_ID) DESC, S.HACKER_ID ASC;